spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=eva_submissions
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.servlet.context-path=/eva/webservices/submission-ws

management.metrics.binders.jvm.enabled=false

spring.cache.type=simple

# HikariCP connection pool settings
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

lsri.clientId=lsri-client-id
lsri.clientSecret=lsri-client-secret
lsri.userinfo.url=lsri-userinfo-url
lsri.token.url=lsri-token-url