name: Run tests

on:
  push:
    branches: [ main, java21 ]
  pull_request:
    branches: [ main, java21 ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [1.8]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.3
        with:
          java-version: ${{ matrix.java-version }}
      - name: Run Maven tests
        run: mvn test -Dapi.version=1.44
